version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Building complete"
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Testing complete"
  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "Deploy complete"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
  build-test-and-deploy:
      jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^beta.*/
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test


              
# workflows:
#   version: 2
#   build-test-and-deploy:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build
#       - deploy:
#           requires:
#             - test
#           filters:
#             branches:
#               ignore: /.*/
#             tags:
#               only: /^beta.*/
